---
# module: rd-ansible-influx-db/tasks/install
# description: Install our required packages for rd-ansible-influx-db

- name: If we enable kapacitor then add this to the package list
  set_fact:
    packages: "{{ packages + [ 'kapacitor' ] }}"
  when: influx_db_enable_kapacitor

- name: Install all required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Make influxdb is started so we can use api
  service:
    name: influxdb
    enabled: true
    state: started
