# Small shim to pull down a remote vagrantfile
require 'open-uri'
require 'openssl'
# ignore warnings for below ssl disable
$VERBOSE = nil

# Disable SSL checks
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

# Define remote
remote_vagrantfile = "https://git.mist.rd.bbc.co.uk/ansible-master-repos/ansible-mist-vagrantfile/raw/master/vagrantfile_ansible_roles"
downloaded_vagrantfile = '.vagrant/downloaded.vagrantfile'

# Download file and then load in
download = open(remote_vagrantfile)
IO.copy_stream(download, downloaded_vagrantfile)

eval File.read(downloaded_vagrantfile)
